name: Linter
on: [push, workflow_dispatch]

jobs:
  lua_lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Linting
        id: action-glua-lint
        uses: TASSIA710/action-glua-lint@master
        with:
          directory: /
